# grype configuration, full definition available at https://oss.anchore.com/docs/reference/grype/configuration/
check-for-app-update: "false"
fail-on-severity: "high"
ignore-wontfix: "wont-fix"
log:
  level: "warn"
search:
  scope: "all-layers"
sort-by: "severity"
