name: Documentation

on:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/documentation.yml"
      - "markdown/.markdownlint.json"
      - "README.md"
  workflow_dispatch:

jobs:
  analyze:
    name: Documentation Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - uses: DavidAnson/markdownlint-cli2-action@v23.1.0
        with:
          config: "markdown/.markdownlint.json"
          globs: "README.md"
          separator: ","
